/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_1;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import static proyecto_1.CronoThread.level;
import static proyecto_1.CronoThread.minutes;
import static proyecto_1.CronoThread.seconds;
import static proyecto_1.Tablero.numLinesRemoved;
import static proyecto_1.Tablero.puntos;
/**
 *
 * @author tcoto
 */
public class Juego extends javax.swing.JFrame {
    
    private Tablero tableroJuego;
    private Juego a = this;
    /**
     * Creates new form Juego
     */
    private CronoThread cronometer;
    private Tetris game;
    public Juego() {
        initComponents();
        setTitle("Tetris");
        
    }

    public void setTextToCrono(String str){
        Tiempo_actual.setText(str);
    }
    public void setTextToLevel(int Level){
        nivel_actual.setText("" +  Level);
    }
    public void setTextToPointsandLines(int Points, int Lines){
        Puntos_actuales.setText("" + Points);
        Lineas_actuales.setText("" + Lines);
    }
    public void sette(String a){
        
    }
    private String setNiceFormat(int number){
        if (number < 10)
            return "0" + number;
        return "" + number;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tiempo_actual1 = new javax.swing.JLabel();
        PanelTableroEnJuego = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonRegresar = new javax.swing.JButton();
        Pausa = new javax.swing.JButton();
        SiguientePieza1 = new javax.swing.JPanel();
        SiguientePieza2 = new javax.swing.JPanel();
        BotonPausa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Tiempo = new javax.swing.JLabel();
        Tiempo_actual = new javax.swing.JLabel();
        Puntos = new javax.swing.JLabel();
        Puntos_actuales = new javax.swing.JLabel();
        BotonIniciar = new javax.swing.JButton();
        Nivel = new javax.swing.JLabel();
        nivel_actual = new javax.swing.JLabel();
        statusbar = new javax.swing.JLabel();
        Lineas = new javax.swing.JLabel();
        Lineas_actuales = new javax.swing.JLabel();

        Tiempo_actual1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tiempo_actual1.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo_actual1.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelTableroEnJuego.setForeground(new java.awt.Color(255, 255, 255));
        PanelTableroEnJuego.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PanelTableroEnJuegoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout PanelTableroEnJuegoLayout = new javax.swing.GroupLayout(PanelTableroEnJuego);
        PanelTableroEnJuego.setLayout(PanelTableroEnJuegoLayout);
        PanelTableroEnJuegoLayout.setHorizontalGroup(
            PanelTableroEnJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        PanelTableroEnJuegoLayout.setVerticalGroup(
            PanelTableroEnJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(70, 110, 196));

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        Pausa.setText("Cargar");
        Pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarActionPerformed(evt);
            }
        });

        SiguientePieza1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout SiguientePieza1Layout = new javax.swing.GroupLayout(SiguientePieza1);
        SiguientePieza1.setLayout(SiguientePieza1Layout);
        SiguientePieza1Layout.setHorizontalGroup(
            SiguientePieza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        SiguientePieza1Layout.setVerticalGroup(
            SiguientePieza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        SiguientePieza2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout SiguientePieza2Layout = new javax.swing.GroupLayout(SiguientePieza2);
        SiguientePieza2.setLayout(SiguientePieza2Layout);
        SiguientePieza2Layout.setHorizontalGroup(
            SiguientePieza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        SiguientePieza2Layout.setVerticalGroup(
            SiguientePieza2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BotonPausa.setText("Pausa");
        BotonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Pausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SiguientePieza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiguientePieza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(SiguientePieza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SiguientePieza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(Pausa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(70, 110, 196));

        Tiempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo.setText("Tiempo:");

        Tiempo_actual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Tiempo_actual.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo_actual.setText("00:00");

        Puntos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Puntos.setForeground(new java.awt.Color(255, 255, 255));
        Puntos.setText("Puntos:");

        Puntos_actuales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Puntos_actuales.setForeground(new java.awt.Color(255, 255, 255));
        Puntos_actuales.setText("0");

        BotonIniciar.setText("Iniciar");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });

        Nivel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nivel.setForeground(new java.awt.Color(255, 255, 255));
        Nivel.setText("Nivel:");

        nivel_actual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nivel_actual.setForeground(new java.awt.Color(255, 255, 255));
        nivel_actual.setText("1");

        statusbar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statusbar.setForeground(new java.awt.Color(255, 255, 255));
        statusbar.setText(" 0");

        Lineas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lineas.setForeground(new java.awt.Color(255, 255, 255));
        Lineas.setText("Lineas");

        Lineas_actuales.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lineas_actuales.setForeground(new java.awt.Color(255, 255, 255));
        Lineas_actuales.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BotonIniciar)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Puntos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Puntos_actuales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lineas)
                                .addGap(18, 18, 18)
                                .addComponent(Lineas_actuales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Tiempo_actual)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nivel_actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Nivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(statusbar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tiempo)
                    .addComponent(Nivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tiempo_actual)
                    .addComponent(nivel_actual))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puntos)
                    .addComponent(Puntos_actuales))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lineas)
                    .addComponent(Lineas_actuales))
                .addGap(33, 33, 33)
                .addComponent(statusbar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTableroEnJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelTableroEnJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelTableroEnJuego.getAccessibleContext().setAccessibleName("");
        PanelTableroEnJuego.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        Tetris_menu Menu = new Tetris_menu();
        Menu.setLocationRelativeTo(null);
        Menu.setVisible(true);
        super.dispose();
        game.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
       String partida = ManejoPartidas.cargaPartidaTexto("partidaTexto.ser", 8);
       ManejoPartidas.Cargar_partida(partida);
       String newTime = setNiceFormat(minutes) + ":" + setNiceFormat(seconds);
       this.setTextToCrono(newTime);
       this.setTextToPointsandLines(puntos, numLinesRemoved);
       this.setTextToLevel(level);
       game.focus();
    }//GEN-LAST:event_BotonCargarActionPerformed

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        // TODO add your handling code here:
        EventQueue.invokeLater(() -> {
            game = new Tetris();
            game.requestFocus();
            game.setVisible(true);
        });
        cronometer = new CronoThread(this);
        cronometer.start();
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void PanelTableroEnJuegoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PanelTableroEnJuegoAncestorAdded
        // TODO add your handling code here:
        //cicloJuego();
    }//GEN-LAST:event_PanelTableroEnJuegoAncestorAdded

    private void BotonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausaActionPerformed
         // TODO add your handling code here:
        //requestFocus();
        game.requestFocus();
        cronometer.pauseThread();
        game.Mapa.pause();
        Pause_menu Pausa = new Pause_menu(cronometer, game.getMapa(), this, game);
        Pausa.setLocationRelativeTo(null);
        Pausa.setVisible(true);
        
    }//GEN-LAST:event_BotonPausaActionPerformed
     
    JLabel getStatusBar() {
        return statusbar;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JButton BotonPausa;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel Lineas;
    private javax.swing.JLabel Lineas_actuales;
    private javax.swing.JLabel Nivel;
    public javax.swing.JPanel PanelTableroEnJuego;
    private javax.swing.JButton Pausa;
    private javax.swing.JLabel Puntos;
    private javax.swing.JLabel Puntos_actuales;
    public javax.swing.JPanel SiguientePieza1;
    public javax.swing.JPanel SiguientePieza2;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel Tiempo_actual;
    private javax.swing.JLabel Tiempo_actual1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nivel_actual;
    private javax.swing.JLabel statusbar;
    // End of variables declaration//GEN-END:variables
public class Tetris extends JFrame {

    private JLabel statusbar;
    public Tablero Mapa;

    public Tetris() {

        initUI();
    }

    private void initUI() {

        statusbar = new JLabel(" 0");
        add(statusbar, BorderLayout.SOUTH);
        Mapa = new Tablero(this, a);
        add(Mapa);
        Mapa.start();

        setTitle("Tetris");
        setSize(235, 590);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    JLabel getStatusBar() {

        return statusbar;
    }
    Tablero getMapa (){
        return Mapa;
    }
    void focus(){
        Mapa.requestFocus();
    }
}
}
